name: Docker

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Main build and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: octopussamples/jenkins-complete-image
